<?php

return [
    'auto_mail' => 'This email is automatically generated by the system, please do not reply to this email',
    'Data_prenotata' => 'Reserved date',
    'Messaggio' => 'Message',
    'Sala_prenota' => 'Reserved room',
    'Numero_di_adulti' => 'Number of adults',
    'Numero_di_bambini' => 'Number of children',
    'Indirizzo_per_la_consegna' => 'Delivery address',
    'Costo_della_consegna_a_domicilio' => 'Home delivery cost',
    'Totale_carrello' => 'Cart total',
    'modalita_consegna_asporto' => 'Delivery method: Takeaway pickup at :name',
    'contatta_tel_mail' => 'Contact :name if you wish to cancel or modify your reservation:',
    'end_copy' => '© 2025 :name. All rights reserved.',
    'Chiama' => 'Call',
    'Visualizza_nella_Dashboard' => 'View in Dashboard',
    'Prodotti_scelti' => 'Selected products',
    'Prodotti_nel_menu' => 'Products in the menu',
    'Opzioni' => 'Options',
    'Ingredienti_extra' => 'Extra ingredients',
    'Ingredienti_rimossi' => 'Removed ingredients',

    'common' => [
        'menu' => 'Menu',
        'product' => 'Product',
    ],

    'emails' => [
        'order_summary' => 'Order Summary',
        'call_name' => 'Call :name',
        'status_cancelled' => 'Canceled',
        'status_confirmed' => 'Confirmed',
        'status_refunded' => 'Refunded',
        'status_pending' => 'Pending',
    ],

    'controllers' => [
        'orders' => [
            'accepted_title' => 'We confirm that your order has been accepted',
            'cancelled_title' => 'We regret to inform you that your order has been cancelled.',
            'refund_subtitle' => 'Your refund will be processed within 5-10 business days.',
        ],
        'reservations' => [
            'accepted_title_full' => 'We confirm that your reservation has been accepted',
            'cancelled_title' => 'Your reservation has been cancelled',
        ],
    ],
];
